return {

  { "LazyVim/LazyVim", enabled = true },
  { "folke/lazy.nvim", enabled = true },
  { "folke/snacks.nvim", enabled = true },
  { "mason-org/mason.nvim", enabled = true },
  { "neovim/nvim-lspconfig", enabled = true },
  { "nvim-treesitter/nvim-treesitter", enabled = true },
  { "williamboman/mason-lspconfig.nvim", enabled = true },
  { "projekt0n/github-nvim-theme", enabled = true },
  { "nvim-neo-tree/neo-tree.nvim", enabled = true },

  { "iamcco/markdown-preview.nvim", enabled = true },
  { "echasnovski/mini.ai", enabled = true },
  { "folke/which-key.nvim", enabled = true },
  { "folke/tokyonight.nvim", enabled = true },
  { "saghen/blink.cmp", enabled = true },
  { "HiPhish/jinja.vim", enabled = true },
  { "echasnovski/mini.icons", enabled = true },
  { "akinsho/bufferline.nvim", enabled = true },
  { "gitsigns.nvim", enabled = false },
  { "MagicDuck/grug-far.nvim", enabled = true },
  { "folke/flash.nvim", enabled = true },
  { "cuducos/yaml.nvim", enabled = true },
  { "echasnovski/mini.pairs", enabled = true },
  { "folke/ts-comments.nvim", enabled = true },
  { "folke/todo-comments.nvim", enabled = true },
  { "andrewferrier/wrapping.nvim", enabled = true },
  { "folke/lazydev.nvim", enabled = true },
  { "nvim-treesitter/nvim-treesitter-textobjects", enabled = true },
  { "windwp/nvim-ts-autotag", enabled = true },
  { "christoomey/vim-tmux-navigator", enabled = true },
  { "folke/noice.nvim", enabled = true },
  { "MunifTanjim/nui.nvim", enabled = true },
  { "nvim-lua/plenary.nvim", enabled = true },
  { "b0o/SchemaStore.nvim", enabled = true },

  -- Disable
  { "fasterius/simple-zoom.nvim", enabled = true },
  { "folke/persistence.nvim", enabled = true },
  { "MeanderingProgrammer/render-markdown.nvim", enabled = true },
  { "nvim-telescope/telescope.nvim", enabled = true },
  { "sindrets/diffview.nvim", enabled = true },
  { "catppuccin", enabled = true },
  { "nvim-tree/nvim-web-devicons", enabled = true },
  { "m4xshen/hardtime.nvim", enabled = true },
  { "stevearc/conform.nvim", enabled = false },
  { "stevearc/oil.nvim", enabled = true },
  { "kylechui/nvim-surround", enabled = true },
  { "ibhagwan/fzf-lua", enabled = true },
  -- Culprit
  { "nvim-lualine/lualine.nvim", enabled = true },
  { "tpope/vim-fugitive", enabled = true },
  { "towolf/vim-helm", enabled = true },
  { "rafamadriz/friendly-snippets", enabled = true },
  { "nvim-telescope/telescope-live-grep-args.nvim", enabled = true },
  { "mfussenegger/nvim-lint", enabled = true },
}
